### ISSUE TITLE
Cypress cannot write to the cache directory due to file permissions

### ISSUE THREAD

**Issue by tmaziere** [CaenCamp/jobs-caen-camp#23]
Je rencontre un soucis de droits d'écriture lors du` make install`, et plus particulièrement au moment d'écrire dans le cache de Cypress (install Docker).

Si j'en crois [https://github.com/cypress-io/cypress/issues/1281](https://github.com/cypress-io/cypress/issues/1281) on aurait peut-être intérêt à préciser CYPRESS_CACHE_FOLDER ([env](https://docs.cypress.io/guides/getting-started/installing-cypress.html#Binary-cache)).

```
error /jobboard/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory: /jobboard/node_modules/cypress
Output:
Cypress cannot write to the cache directory due to file permissions

See discussion and possible solutions at
https://github.com/cypress-io/cypress/issues/1281

----------

Failed to access /.cache/Cypress:

EACCES: permission denied, mkdir '/.cache'
```
(MacOS 10.14.6)

Avis bienvenus !

**Comment by gaelreyrol** [comment]
Il me semble qu'il y a un rapport avec #18 non ?

**Comment by FanchGadjo** [comment]
Je n'ai pas ce problème sous Debian 10. Voilà ma config, si ça peut aider qqun : 
```
$ docker --version
Docker version 19.03.5, build 633a0ea838
$ node --version
v12.14.1
$ npm --version
6.13.4
$ yarn --version
1.21.1
$ node_modules/.bin/cypress --version
Cypress package version: 3.8.1
Cypress binary version: 3.8.1
```

Dans la doc, je lis : 

> As of version 3.0, Cypress downloads the matching Cypress binary ...
> MacOS: `~/Library/Caches/Cypress`

https://docs.cypress.io/guides/getting-started/installing-cypress.html#Binary-cache

**Comment by gaelreyrol** [comment]
@quen2404 avait eu ce problème là à la dernière session des CCCs sur son Mac Book Pro.

**Comment by quen2404** [comment]
ouai c'etait parce que la commande `shell` n'etait pas disponible...

**Comment by quen2404** [comment]
en modifiant dans le Dockerfile:
```
export UID = $(shell id -u)
export GID = $(shell id -g)
```
par ça:
```
export UID = $(id -u)
export GID = $(id -g)
```
ça avait fonctionné

**Comment by tmaziere** [comment]
Bien vu, ça fonctionne.
