### ISSUE TITLE
Un store pour le front Svelte

### ISSUE THREAD

**Issue by tmaziere** [CaenCamp/jobs-caen-camp#24]
Histoire de faire la jonction entre le front et l'API, j'ai commencé à jeter un œil aux stores "à la Svelte" : https://svelte.dev/examples#custom-stores

Ça semble nettement [plus light que Redux](https://www.youtube.com/watch?v=goTc0HM8Tpo), mais j'imagine que ça pourrait faire le job.

Avez-vous des réserves ou des préconisations dans ce domaine ?

**Comment by FanchGadjo** [comment]
Pas d'avis sur le sujet, mais l'implémentation semble simple et élégante. :+1:

**Comment by Nexoid** [comment]
Pas beaucoup plus d'avis sur l'implementation. Mais ca semble être la plus simple et la plus légère, et je doute qu'on est besoin de plus :)

**Comment by alexisjanvier** [comment]
Je suis pour aussi ! La gestion des stores semble faire partie intégrante de Svelte, autant en profiter au maximum :+1:
