### ISSUE TITLE
Svelte router

### ISSUE THREAD

**Issue by quen2404** [CaenCamp/jobs-caen-camp#26]
Bonjour à tous, 
j'ai une petite question concernant l'un des choix pour la partie frontend: le router de svelte.
pourquoi etre parti sur `svelte-routing` et non sur la solution officiel [Sapper](https://sapper.svelte.dev/) ?

**Comment by gaelreyrol** [comment]
C'est quelque chose qu'on avait abordé il me semble et Sapper semblait "trop" évolué dans le sens où nous n'avous pas d'expérience sur Svelte. Donc pour ne pas surcharger la stack avec quelque chose qu'on ne maîtrise pas.

**Comment by alexisjanvier** [comment]
Yop. En vrai, toute la partie Svelte vient d'une PR (https://github.com/CaenCamp/jobs-caen-camp/pull/16) en mode sandbox découverte de Svelte ! On l'a mergé pour chopper principalement le switch de Rollup à Webpack.
Se posait effctivement la question du routeur, avec cette remarque que celui utilisé était quand même pas terrible ! 
L'équipe de KNPLabs a bossé sur le leur https://www.npmjs.com/package/svelters-router Sans doute une bonne piste !

**Comment by alexisjanvier** [comment]
Concernant `Sapper` je me rappel que tu te posais la question @gaelreyrol sur le pourquoi ne pas partir dessus ! ^^
C'est vrai que de mon côté, et ne connaissant pas Svelte, j'étais pas chaud pour rajouter toutes la couche Sapper sans connaitre ce qu'il y avait derrière.
