### ISSUE TITLE
Mise en place de yarn workspace avec CRA

### ISSUE THREAD

**Issue by Clebiez** [CaenCamp/jobs-caen-camp#38]
Avec la mise en place de react-admin, il s'impose la nécessité d'utiliser les workspaces yarn pour mieux gérer les différents "packages".

CF cette PR : https://github.com/CaenCamp/jobs-caen-camp/pull/36

J'ai réussi à mettre en place, sur un autre projet, les workspaces avec plusieurs CRA en utilisant craco, un petit tool qui permet d'override la config webpack pour passer les composants reacts des packages sur babel-loader :

https://github.com/gsoft-inc/craco

le fichier craco.config.js en question :

```JavaScript
const path = require('path');
const { getLoader, loaderByName } = require('@craco/craco');

// Transform into an array if you want to include more babelized packages

const absolutePath = path.join(__dirname, 'packages/core/src');
module.exports = {
  webpack: {
    alias: {},
    plugins: [],
    configure: webpackConfig => {
      const { isFound, match } = getLoader(webpackConfig, loaderByName('babel-loader'));
      if (isFound) {
        const include = Array.isArray(match.loader.include)
          ? match.loader.include
          : [match.loader.include];
        include.push(absolutePath); // Add core packages to the babel-loader list. Use concat in case of array.
        match.loader.include = include; // Push it to the config

      }

      return webpackConfig;
    },
  },
};

```

Cette snippet permet dans un package, de consommer des composants d'un autre package en les passant via babel-loader.
ll suffit ensuite d'utiliser les commandes craco à la place de react-scripts dans le package.json en question.

Que pensez-vous de ce système ?

Je l'ai mis en place dans ma boîte, ça fait 3 semaines que ça tourne bien. 
Nous utilisions avant https://github.com/react-workspaces/create-react-app mais il ne  semble plus activement maintenu et c'est un remplaçant à CRA tandis que Craco n'est qu'une couche d'override.

**Comment by alexisjanvier** [comment]
Ca me semble bien, je suis vraiment pas fan de la solution `not-in-yarn-workspace` ! Je :+1:
