### ISSUE TITLE
Sécurisation de l’administration

### ISSUE THREAD

**Issue by alexisjanvier** [CaenCamp/jobs-caen-camp#47]
Nous avons mis en place une administration basée sur react-admin. Avant de pouvoir mettre en ligne le site et son administration, il faut mettre en place une authentification sur react-admin.

**Comment by Nexoid** [comment]
Je suppose que le plus simple serait de mettre en place une authentification via JWT ?
Pour ce qui est des rôles, pour le moment il n'y a pas de besoin spécifique à en établir, mais est-ce que c'est prévu par la suite et faut-il l'anticiper ?

**Comment by alexisjanvier** [comment]
Je suis d'accord. Pour le moment, l'authentification ne va concerner que l'interface d'administration, et donc des comptes de types admin permettant d'ajouter/editer/supprimer des offres d'emploi. Ce peut donc sans problème être des comptes gérés dans notre base de donnée, avec une authentification basée sur un token JWT et un cookie. Cela répondra parfaitement à la problématique actuelle de mise en ligne.

Il faudra effectivement prévoir pour plus tard la possibilité de créer des comptes permettant aux entreprises de poster elles-même les offres d'emploi, mais cela va sans doute nécessitter pas mal de discussions, si l'on aborde en profondeur le choix du type d'authentification pour ce besoin, et la question de propriété des données liée...
