### ISSUE TITLE
Refonte de la rédaction de la requête côté react-admin

### ISSUE THREAD

**Issue by Keksoj** [CaenCamp/jobs-caen-camp#71]
Après avoir refondu la gestion de la [pagination](https://github.com/CaenCamp/jobs-caen-camp/pull/62), du [tri](https://github.com/CaenCamp/jobs-caen-camp/pull/66) et des [filtres](https://github.com/CaenCamp/jobs-caen-camp/pull/69), il serait chouette de mettre à jour le front (en tout cas React-admin) pour qu'il ne tente plus d'appeler le back ainsi :

```
job-postings?filter=%7B%22jobStartDate_before%22%3A%222020-05-05%22%7D&order=ASC&page=1&perPage=10&sort=name
```

mais ainsi : 

```
job-postings?jobStartDate:lt=2020-05-05&sortBy=title&orderBy=ASC&currentPage=1&perPage=10
```
Le contrat OpenApi contient les specs nécessaires, d'ailleurs consultables avec Swagger sur l'endpoint `/documentation` de l'API.

Je vais me pencher dessus, même si je ne connais pas encore Svelte ou react.
Je pense que ça doit être une bonne porte d'entrée dans le code du front, aussi je mets le label `good first issue`.

**Comment by alexisjanvier** [comment]
@Keksoj C'est fixé dans la pr https://github.com/CaenCamp/jobs-caen-camp/pull/72
Sur ce commit https://github.com/CaenCamp/jobs-caen-camp/pull/72/commits/ed2440a6b7042cd74344efd81ee7bbba2d8bb37a

**Comment by Keksoj** [comment]
Très juste je viens de voir le code, merci !
