### ISSUE TITLE
Mise en place de style de code

### ISSUE THREAD

**Issue by alexisjanvier** [CaenCamp/jobs-caen-camp#8]
Eslint, hysky pour hook git (https://github.com/typicode/husky), conf vscode, etc ...

**Comment by gaelreyrol** [comment]
Je propose d'ajouter les recommandations d'extensions vscode, commitlint via husky ainsi qu'un fichier editorconfig

**Comment by alexisjanvier** [comment]
Je te laisse faire le commit ? En fait, j'utilise presque plus vscode, et je connais pas editorconfig ...
