### ISSUE TITLE
Mise en place des tests

### ISSUE THREAD

**Issue by alexisjanvier** [CaenCamp/jobs-caen-camp#9]
Proposition :

- Jest pour les tests unitaires (front et back).
- Testing Library pour Svelte (https://testing-library.com/docs/svelte-testing-library/intro)
- Frisby.js https://www.frisbyjs.com/ pour les tests fonctionnels de l'API
- Cypress pour les test e2e du front
- Github action pour la CI

**Comment by gaelreyrol** [comment]
Perso ça me va, j'ai commencé à intégrer cypress dans la branche `setup-tests`

**Comment by alexisjanvier** [comment]
@gaelreyrol Cool :) Tu fais toute la stack, ou tu veux que je commence la mise en place de jest sur une autre branche ?

**Comment by gaelreyrol** [comment]
@alexisjanvier Je peux faire tout la stack oui et si il y a des choses à ajuster tu pourras reprendre derrière :)

**Comment by alexisjanvier** [comment]
@gaelreyrol Ok :+1:  J'ai poussé une branche sur laquelle j'avais commencé jest (https://github.com/CaenCamp/jobs-caen-camp/tree/setup-test-jest) ! C'est juste pour pour info et ok pour moi, je ferais la review sur ta branche si je vois des trucs !

**Comment by gaelreyrol** [comment]
Ça marche, je vais intégrer ce que tu as fait alors

**Comment by gaelreyrol** [comment]
Je te propose qu'on sorte la mise en place du CI dans une autre issue
